controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_Musique_add:
    path: /Musique/add
    controller: App\Controller\MusiqueController::add
    methods: [GET, POST]